---
author: "Earle"
date: "`r Sys.Date()`"
output: 
  html_document: 
    self_contained: no
---

```{r, include=FALSE}
### battery publishing ###

library(ggplot2)
library(tidyverse)
library(blastula)

#get deployed gliders
deployedGliders <- read.csv("/echos/deployedGliders.txt", 
                            sep = "",
                            header = FALSE)
colnames(deployedGliders)[1] = "Name"
colnames(deployedGliders)[2] = "ahrCap"

#only process "real" ones
deployedGliders <- deployedGliders %>%
  filter(!str_starts(Name,"#")) #remove any commented lines

#initialize list
gliders_live <- list()
for (i in deployedGliders$Name){
  
  #load latest live data file
  load(paste0("/echos/", i, "/glider_live.RData"))
  
  if (ahrCap$ahrCap > 0){
    recoDays <- format(round(((ahrCap$ahrCap*.9)-ahrUsed)/ahr3day, 2), nsmall = 2) #calculate days til 10% abort level
    
    # fileConn<-file(paste0("/echos/", i , "/battLeft.txt")) #open file connection
    # writeLines(c(paste0("Subject: Daily summary for ", as.character(i)), #write email subject
    #              paste0("Approximate time until 10% abort level: ", format(round(recoDays, 2), nsmall = 2), " days (calculated with 72hr usage)"), #write recoDays var as char
    #              paste0("Total mission amphr usage: ", format(round(ahrAllday, 2), nsmall = 2), " amphr/day"),
    #              paste0("Last 24hr amphr usage: ", format(round(ahr1day, 2), nsmall = 2), " amphr/day"),
    #              paste0("Last 72hr amphr usage: ", format(round(ahr3day, 2), nsmall = 2), " amphr/day")
    #              ), 
    #            sep = "\n",
    #            fileConn)
    # close(fileConn) #close it
    coulombs <- gliderdf %>%
  select(c(m_present_time, m_coulomb_amphr_total)) %>%
  filter(m_coulomb_amphr_total > 0) %>%
  mutate(day = floor_date(m_present_time,
                          unit = "days")) %>%
  group_by(day) %>%
  mutate(dailyAhr = (max(m_coulomb_amphr_total)-min(m_coulomb_amphr_total))/(as.numeric(max(m_present_time))-as.numeric(min(m_present_time)))*86400) %>%
  #select(c(day, meanBatt)) %>%
  distinct(day, dailyAhr)

couLive <- ggplot(
  data = 
    coulombs,
  aes(x=day,
      y=dailyAhr,
  )) +
  geom_point(
    size = 2,
    na.rm = TRUE
  ) +
  theme_bw() +
  labs(title = "Daily Power Usage",
       y = "Ahrs",
       x = "Date") +
  theme(plot.title = element_text(size = 32),
        axis.title = element_text(size = 20),
        axis.text = element_text(size = 16))
  }
  
}
```

---
title: "`r i` Summary"
---

This is the daily summary for `r i`. For full data, see <http://earle.marine.usf.edu:3838/thebrewery/>.

## Battery Summary

Approximate time until 10% abort level: `r recoDays` days (calculated using 72hr usage)

```{r, echo=FALSE}
add_ggplot(plot_object = couLive)
#plot(couLive)
```

